Unsubscribe sleep event on disconnect
mysteriumnetwork/node pull request #2600
Opened 2020-09-07 08:13 UTC by zolia

2020-09-07 08:37 UTC, soffokl approved these changes

2020-09-08 06:23 UTC, zolia commented
Will rework to use eventBus only on node startup / shutdown

2020-09-08 08:08 UTC, Waldz requested changes

2020-09-08 08:08 UTC, Waldz commented on core/connection/manager.go
> +	m.eventBus.Unsubscribe(sleep.AppTopicSleepNotification, m.handleSleepEvent)
Avoid subscribing on runtime. To avoid problems like this, or multiple subscriptions, races, memory leaks.

2020-09-08 10:40 UTC, Waldz approved these changes

2020-09-08 10:42 UTC, merged