Remake logging in end user products
mysteriumnetwork/node pull request #2842
Opened 2020-11-19 11:51 UTC by tomasmik

Now in compiled `myst cli` and future applications, logging to terminal will be disabled.
This is required in order to move along with the user friendly CLI apps.

The end user does not need to see the 50 lines of debugging messages printed when you launch `myst cli`, nor does he need the `zerolog` messages.

Now instead of:

```sh
» identities register 0x5d370ab418179d7de9410899249604d54485b860
2020-11-19T13:47:03.522 ERR tequilapi/client/http_client.go:123      >  error="server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x5d370ab418179d7de9410899249604d54485b860/register). Possible error: failed identity registration request: server response invalid: 400 Bad Request (https://testnet-transactor.mysterium.network/api/v1/identity/register){\"error\":{}}"
[WARNING] could not register identity: server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x5d370ab418179d7de9410899249604d54485b860/register). Possible error: failed identity registration request: server response invalid: 400 Bad Request (https://testnet-transactor.mysterium.network/api/v1/identity/register){"error":{}}
```

The end user sees this:
```sh
» identities register 0x5d370ab418179d7de9410899249604d54485b867
[WARNING] could not register identity: server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x5d370ab418179d7de9410899249604d54485b867/register). Possible error: failed identity registration request: server response invalid: 400 Bad Request (https://testnet-transactor.mysterium.network/api/v1/identity/register){"error":{}}
```

It's not perfect, but better.

Closes: https://github.com/mysteriumnetwork/node/issues/2840

2020-11-19 12:50 UTC, vkuznecovas requested changes
This seems way overcomplicated for such a simple objective. 

Add a flag that enables verbose logging to stdout, log to file by default? 
There would be no need to split this for separate commands either.

2020-11-19 12:56 UTC, tomasmik commented
> This seems way overcomplicated for such a simple objective.
> 
> Add a flag that enables verbose logging to stdout, log to file by default?
> There would be no need to split this for separate commands either.

My reasoning for the split between different commands is that, I don't see a point in running `node daemon` and not seeing the console logs. Though I can remove that no problem.
The flag though, I was also thinking about it too just wasn't sure if it's of any use.

2020-11-19 13:10 UTC, vkuznecovas commented
> > This seems way overcomplicated for such a simple objective.
> > Add a flag that enables verbose logging to stdout, log to file by default?
> > There would be no need to split this for separate commands either.
> 
> My reasoning for the split between different commands is that, I don't see a point in running `node daemon` and not seeing the console logs. Though I can remove that no problem.
> The flag though, I was also thinking about it too just wasn't sure if it's of any use.

That's why I was talking about a totally separate binary. You can approach the problem completely differently here, but we'll still need the CLI as is at least for developer testing.

2020-11-20 06:04 UTC, mdomasevicius commented on cmd/commands/cli/command.go
> +		Name:   CliCommandName,
Actually according to go bible this should be `CLICommandName` or `cliCommandName` as CLI is an acronym

2020-11-20 06:11 UTC, mdomasevicius commented on cmd/mysterium_node/mysterium_node.go
> +func readyOnceFunc() cli.BeforeFunc {
I think this is a terrible name, `configureCLILogging` even just `configureLogging` is better and would reduce comment docs by a whole line

2020-11-20 06:13 UTC, mdomasevicius commented on cmd/mysterium_node/mysterium_node.go
> +			err = logconfig.ConfigureUI(&logconfig.LogOptions{
How about `logconfig.BootstrapCLI(...)` - package gives away the context and function name can explain the rest?

2020-11-20 06:19 UTC, mdomasevicius commented
> That's why I was talking about a totally separate binary. You can approach the problem completely differently here, but we'll still need the CLI as is at least for developer testing.

Separate binary for CLI?

2020-11-20 06:22 UTC, soffokl reviewed
I don't think that we need to have logs for CLI. Even log to file looks like a bad idea.
1) If you are going to write to the same configured file that used for the daemon, it will create a mess in the log file when 2 processes trying to write to the same file at the same time. 
2) CLI should not print logs, only useful output that can be redirected to the pipe for the next command `$ myst cli identity list | myst cli identity register`

If a user wants to have a debug output of the CLI command we can redirect it to the different streams. Debug goes to the STDERR, useful output goes to the STDOUT.

Logging for daemon should go to the STDOUT, since processes that execute it has better log maintenance(systemd, docker, whatever)

Separate binary for CLI will make a delivery process more complicated. Everyone loves golang for the single binary file with no other dependencies. And both binaries reuse the same codebase. I think it's simpler to keep as one file.

2020-11-20 06:22 UTC, soffokl commented on cmd/mysterium_node/mysterium_node.go
> +				log.Error().Err(err).Msg("configuring logger for ui")
```suggestion
				log.Error().Err(err).Msg("Failed to configure logger for ui")
```

2020-11-20 06:29 UTC, tomasmik commented
> I don't think that we need to have logs for CLI. Even log to file looks like a bad idea.
> 
> 1. If you are going to write to the same configured file that used for the daemon, it will create a mess in the log file when 2 processes trying to write to the same file at the same time.

We log to a different file here, which is named according to the command, `cli` in this case and it's only really useful in cases where someone would like to share the logs with us when something is not working as it should.

>Separate binary for CLI will make a delivery process more complicated. Everyone loves golang for the single binary file with no other dependencies. And both binaries reuse the same codebase. I think it's simpler to keep as one file.

I think that the separate binary wasn't about this, current `myst cli` but this: https://github.com/mysteriumnetwork/node/issues/2837

2020-11-20 06:31 UTC, soffokl commented on logconfig/config.go
> +// ConfigureUI configures the logger for user interface CLI
UI for CLI looks weird. User interface for command-line interface.

2020-11-20 06:32 UTC, soffokl commented
> We log to a different file here, which is named according to the command, cli in this case and it's only really useful in cases where someone would like to share the logs with us when something is not working as it should. Though we can explore writing to stderr

CLI just does calls to TequilAPI, I think it's enough to have just logs from the daemon, it already should include everything. Why do we need to have extra logs for CLI?

2020-11-20 07:39 UTC, tomasmik commented
Everyone is on a different page. Let's groom this.

2020-11-20 07:39 UTC, closed without merging