Remake logging in end user products
mysteriumnetwork/node pull request #2853
Opened 2020-11-25 11:43 UTC by tomasmik

Before:
```sh
» identities register 0x5d370ab418179d7de9410899249604d54485b860
2020-11-19T13:47:03.522 ERR tequilapi/client/http_client.go:123      >  error="server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x5d370ab418179d7de9410899249604d54485b860/register). Possible error: failed identity registration request: server response invalid: 400 Bad Request (https://testnet-transactor.mysterium.network/api/v1/identity/register){\"error\":{}}"
[WARNING] could not register identity: server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x5d370ab418179d7de9410899249604d54485b860/register). Possible error: failed identity registration request: server response invalid: 400 Bad Request (https://testnet-transactor.mysterium.network/api/v1/identity/register){"error":{}}
```

Now:
```sh
» identities register 0x5d370ab418179d7de9410899249604d54485b867
[WARNING] could not register identity: server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x5d370ab418179d7de9410899249604d54485b867/register). Possible error: failed identity registration request: server response invalid: 400 Bad Request (https://testnet-transactor.mysterium.network/api/v1/identity/register){"error":{}}

You can still force the verbose logging with `logverbose` flag.
Logging is configured per command.

2020-11-25 12:34 UTC, vkuznecovas requested changes

2020-11-25 12:34 UTC, vkuznecovas commented on config/flags_node.go
> +		Usage: "If given loggin becomes more verbose",
```suggestion
		Usage: "If provided logging becomes more verbose",
```

2020-11-25 12:34 UTC, vkuznecovas requested changes

2020-11-25 12:34 UTC, vkuznecovas commented on config/flags_node.go
> +		Name:  "log-verbose",
-verbose, -v would be more standard.

2020-11-25 13:15 UTC, vkuznecovas approved these changes

2020-11-26 03:00 UTC, soffokl approved these changes

2020-11-26 07:40 UTC, merged