Node UI password rework
mysteriumnetwork/node pull request #2978
Opened 2021-01-06 08:16 UTC by tomasmik

* Reworked how node password is stored: we now store a password in a separate file on the users machine
* Added a migration to migrate the current password that user has set to be stored in a file (works for testnet and testnet2)
* Fixed the reset command, it now resets users password to default node configured password
* We no longer display debug information when reset command is run

Current config workflow has led to some unwanted workflows which could be remedied only by improving how we handle the config.

2021-01-06 08:29 UTC, vkuznecovas requested changes

2021-01-06 08:29 UTC, vkuznecovas commented on core/node/options_directory.go
> +func GetOptionsDirecotryDB(networkSubdir string) string {
spelling

2021-01-06 08:30 UTC, soffokl approved these changes

2021-01-06 08:30 UTC, soffokl commented on core/auth/credentials.go
> +// returns a new credentials manager,which can be used to validate or alter
```suggestion
// returns a new credentials manager, which can be used to validate or alter
```

2021-01-07 10:51 UTC, vkuznecovas approved these changes

2021-01-08 11:22 UTC, merged