Add static binary build option
mysteriumnetwork/node pull request #3663
Opened 2021-07-23 08:11 UTC by Snawoot

Makes build script accept `BUILD_STATIC` environment variable to make static binaries.

This way it is possible to build standalone Go binary with

```
BUILD_STATIC=1 make build
```

command.

Allows us to run `node` in a distro-agnostic way w/o any dependencies.

2021-07-23 08:21 UTC, tadaskay commented
We use mage for build and these bash scripts are legacy. Your changes should go to the corresponding mage targets.

2021-07-23 08:22 UTC, tadaskay requested changes
See the above comment

2021-07-23 12:23 UTC, Snawoot commented
@tadaskay 

Thanks!

Implemented changes for magefiles. These changes only touching standalone builds for Linux because other platforms have CGO dependency.

2021-07-23 13:09 UTC, tadaskay approved these changes

2021-07-26 03:17 UTC, soffokl approved these changes

2021-07-26 08:12 UTC, mdomasevicius commented on ci/packages/build.go
> +	return buildBinaryFor(source, target, targetOS, targetArch, false)
Just a thought that any further extensions of `buildBinaryFor` signatures could be done as `buildBinaryFor(..., opts... BuildOptions)` for better readability.

2021-07-26 08:12 UTC, mdomasevicius approved these changes

2021-07-26 10:50 UTC, vkuznecovas approved these changes

2021-07-26 12:09 UTC, merged