Avoid side effects for configs while merging
mysteriumnetwork/node pull request #3797
Opened 2021-08-13 12:54 UTC by mdomasevicius

After fetching merge config, default config map gets overwritten, this may be a cause of some weird issues

2021-08-13 12:55 UTC, tomasmik approved these changes

2021-08-13 13:32 UTC, Snawoot requested changes
Here is how this routine works:

1. Shared lock acquired for reading. There will be no changes in default, user and cli maps past this point.
2. Temporary map created.
3. This map gets filled with data from other maps. Submaps linked to temporary map by reference.
4. Temporary map deepcopied to result. No references to shared data past this point.
5. Shared lock released.

Why do we need to deepcopy each map we're copying into result map under read lock if result will be deepcopied either way?

2021-08-13 13:55 UTC, Snawoot approved these changes
Alright, now I get it. Submaps are linked into new temporary map by reference and therefore will be updated when temp. map will be used as destination in next merge. Good catch!

2021-08-13 18:19 UTC, mdomasevicius commented
> Alright, now I get it. Submaps are linked into new temporary map by reference and therefore will be updated when temp. map will be used as destination in next merge. Good catch!

Actually, I was a bit lazy to go over the recursive code and just made `deep copies` as a quick fix. :)

2021-08-16 01:51 UTC, soffokl approved these changes

2021-08-16 05:35 UTC, merged