Support withdrawing to specific chain
mysteriumnetwork/node pull request #3953
Opened 2021-09-14 12:11 UTC by mdomasevicius

2021-09-14 12:14 UTC, tomasmik approved these changes

2021-09-15 03:08 UTC, soffokl approved these changes

2021-09-15 06:41 UTC, vkuznecovas requested changes

2021-09-15 06:41 UTC, vkuznecovas commented on tequilapi/endpoints/transactor.go
>  	err = te.promiseSettler.Withdraw(chainID, identity.FromAddress(req.ProviderID), common.HexToAddress(req.HermesID), common.HexToAddress(req.Beneficiary))
this chain ID determines only from which chain to withdraw, therefore your changes do not accomplish what you want them to accomplish.

You'll need changes to `func (aps *hermesPromiseSettler) Withdraw(chainID int64, providerID identity.Identity, hermesID, beneficiary common.Address) error`. 

The method probably has to include two chain ids: to and from. Currently, the method internally uses:

`aps.config.L1ChainID` -> the chain to withdraw to
`chainID` -> the chainID that was passed as the chain that the withdrawal is originating from.

2021-09-15 13:46 UTC, vkuznecovas approved these changes

2021-09-15 15:40 UTC, merged