Prevent code from a panic if dns list is empty
mysteriumnetwork/node pull request #5252
Opened 2022-06-28 15:40 UTC by andrey-mysterium

Signed-off-by: Andrey <andreyt@mysterium.network>

2022-06-28 15:48 UTC, Snawoot requested changes
Will still panic if `cfg.DNS` slice nil or empty.

2022-06-28 16:37 UTC, Snawoot approved these changes

2022-06-29 02:44 UTC, soffokl approved these changes

2022-06-29 02:44 UTC, soffokl commented on services/wireguard/endpoint/proxyclient/client_test.go
> + * Copyright (C) 2018 The "MysteriumNetwork/node" Authors.
For new files, this should be set to the current date. 
```suggestion
 * Copyright (C) 2022 The "MysteriumNetwork/node" Authors.
```

2022-07-04 03:06 UTC, merged