New API for extended monitoring failure statuses
mysteriumnetwork/node pull request #5331
Opened 2022-07-25 14:22 UTC by andrey-mysterium

2022-07-26 03:51 UTC, soffokl requested changes
The first commit is again called `initial commit`. 
`Initial commit` is created only once per repository and should never be used in the same repo again. 
If every PR will contain an `initial commit`, we will have 5331 `initial commits` in the `master`.

2022-07-26 03:51 UTC, soffokl commented on core/node/node_monitoring_agent_tracker.go
> +// MonitoringAgentStatuses a object represent a [service_type][status]amount of statuses for each status type
```suggestion
// MonitoringAgentStatuses a object represent a [service_type][status]amount of statuses for each service type.
```

2022-07-26 03:51 UTC, soffokl commented on core/quality/mysterium_morqa.go
> +// ProviderStatuses fetch provider connectivity statuses from prometheus (monitoring agent)
```suggestion
// ProviderStatuses fetch provider connectivity statuses from quality oracle.
```

2022-07-26 03:51 UTC, soffokl commented on core/quality/mysterium_morqa.go
> +		return nil
```suggestion
		return err
```

2022-07-26 03:51 UTC, soffokl commented on core/quality/mysterium_morqa.go
> +		log.Warn().Err(err).Msg("Failed to request provider monitoring agent statuses")
```suggestion
		log.Error().Err(err).Msg("Failed to request provider monitoring agent statuses")
```

2022-07-26 03:51 UTC, soffokl commented on core/quality/mysterium_morqa.go
> +		return nil
```suggestion
		return err
```

2022-07-26 03:51 UTC, soffokl commented on core/quality/mysterium_morqa.go
> +		log.Warn().Err(err).Msg("Failed to create provider monitoring agent statuses request")
```suggestion
		log.Error().Err(err).Msg("Failed to create provider monitoring agent statuses request")
```

2022-07-26 03:51 UTC, soffokl commented on core/quality/mysterium_morqa.go
> +		log.Warn().Err(err).Msg("Failed to parse provider monitoring agent statuses")
```suggestion
		log.Error().Err(err).Msg("Failed to parse provider monitoring agent statuses")
```

2022-07-26 03:51 UTC, soffokl commented on core/quality/mysterium_morqa.go
> +		return nil
```suggestion
		return err
```

2022-07-26 03:51 UTC, soffokl commented on tequilapi/contract/node.go
> +// MonitoringAgentResponse a monitoring agent statuses reflects amount of connectivity statuses for each service_type and status
```suggestion
// MonitoringAgentResponse reflects amount of connectivity statuses for each service_type.
```

2022-07-26 03:51 UTC, soffokl commented on tequilapi/endpoints/nat.go
> +
Why is this in the `nat.go` file?

2022-07-27 07:13 UTC, soffokl approved these changes

2022-07-27 09:39 UTC, tomasmik commented on core/quality/mysterium_morqa.go
> +
This is a useless empty line

2022-07-27 09:39 UTC, tomasmik commented on core/quality/mysterium_morqa.go
> +		log.Error().Err(err).Msg("Failed to create provider monitoring agent statuses request")
`log.Error().Err(err)` and `log.Err(err)` do the same thing, so not a lot reason to also add that `Error()`

2022-07-27 09:39 UTC, tomasmik commented on tequilapi/endpoints/node.go
> +		utils.WriteAsJSON(contract.MonitoringAgentResponse{Error: err.Error()}, c.Writer, http.StatusInternalServerError)
you're missing a return here.

2022-07-27 09:42 UTC, andrey-mysterium commented on tequilapi/endpoints/node.go
> +		utils.WriteAsJSON(contract.MonitoringAgentResponse{Error: err.Error()}, c.Writer, http.StatusInternalServerError)
> you're missing a return here.

tanks!

2022-07-27 11:52 UTC, tomasmik approved these changes

2022-07-27 13:15 UTC, merged